In [30]:
import pandas as pd
import os
from haversine import haversine

In [31]:
#os.getcwd()

In [32]:
df=pd.read_csv("LatLong.csv", header =0)

In [33]:
df2=df[:42]

In [34]:
df2

   PLANT        LAT       LONG
0   AHOS  36.286822 -76.984681
1   ALBE  35.854600 -77.055500
2   ALEX  38.804836 -77.046921
3   ALTA  37.111800 -79.285600
4   BLUE  38.149593 -79.072556
5   CAST  37.466890 -77.447000
6   CHAR  38.029305 -78.476677
7   CHES  36.768208 -76.287491
8   CHUC  36.728191 -76.583191
9   ELIZ  36.302200 -76.223228
10  EMER  37.466890 -77.447000
11  ERIC  37.540726 -77.436050
12  FAIR  38.846226 -77.306374
13  FARM  37.302097 -78.391937
14  FISH  38.099000 -78.969200
15  FRED  38.303200 -77.460500
16  GLOU  37.445229 -76.559448
17  HERN  38.969730 -77.383873
18  KHWK  36.066422 -75.693481
19  LEES  39.108002 -77.550636
20  MIDL  37.503651 -77.651749
21  MILL  41.765800 -72.673400
22  NNCK  37.777639 -76.513563
23  NORF  36.850769 -76.285873
24  ORAN  38.249035 -78.013983
25  PENI  37.028271 -76.342339
26  PETE  37.205502 -77.387642
27  RICH  37.540726 -77.436050
28  ROAN  36.456039 -77.657227
29  ROCK  37.780941 -79.446564
30  SBOS  36.698749 -78.901399
31  SHEN  38.881778 -78.505843
32  SMTR  37.466890 -77.447000
33  SPRI  38.785809 -77.187248
34  SSID  36.726545 -78.129131
35  VBCH  36.852924 -75.977982
36  WARR  38.713840 -77.795563
37  WILL  37.270702 -76.707458
38  WOOD  38.663460 -77.245651

In [35]:
it = df2.iterrows()

In [37]:
locations = {}
for l in it:
    locations[l[1][0]]=(l[1][1].LAT, l[1][2].LONG )

In [38]:
mat =[]
for df2_0 in locations:
    row =[]
    for df2_1 in locations:
        distance = haversine(df2_0, df2_1, unit='mi')
        row.append(distance)
    mat.append(row)
mat

TypeError: cannot unpack non-iterable int object